# Generated by Django 6.0.1 on 2026-01-13 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='nome_sem_cadastro',
            new_name='nome_destinatario',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
